// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBYNaNbfKbUzFywHa1Zp-TTbJofZS2IxAs',
    appId: '1:894293475495:web:b766fd1788b639a2cadb82',
    messagingSenderId: '894293475495',
    projectId: 'fluttersamplecicd-84cb1',
    authDomain: 'fluttersamplecicd-84cb1.firebaseapp.com',
    storageBucket: 'fluttersamplecicd-84cb1.appspot.com',
    measurementId: 'G-Y5DE52M63H',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD1Sm6dENukmlGmRirhqVS7PVfqRNRZjAA',
    appId: '1:894293475495:android:b4a27edbbf7cd30fcadb82',
    messagingSenderId: '894293475495',
    projectId: 'fluttersamplecicd-84cb1',
    storageBucket: 'fluttersamplecicd-84cb1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAUfSFtXWSAp9031frv5YDgRdTDkBszFsw',
    appId: '1:894293475495:ios:db54eeb3a9f892e4cadb82',
    messagingSenderId: '894293475495',
    projectId: 'fluttersamplecicd-84cb1',
    storageBucket: 'fluttersamplecicd-84cb1.appspot.com',
    iosClientId: '894293475495-qvtf2rst9i91260om4add9jc6hf66t89.apps.googleusercontent.com',
    iosBundleId: 'com.surya.example.flutterSampleCicd',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAUfSFtXWSAp9031frv5YDgRdTDkBszFsw',
    appId: '1:894293475495:ios:74389236147f5398cadb82',
    messagingSenderId: '894293475495',
    projectId: 'fluttersamplecicd-84cb1',
    storageBucket: 'fluttersamplecicd-84cb1.appspot.com',
    iosClientId: '894293475495-boeg4ube1aefvb69r7jqoaqkc5ca6983.apps.googleusercontent.com',
    iosBundleId: 'com.surya.example.flutterSampleCicd.RunnerTests',
  );
}
